### ISSUE TITLE
USB device found (Astra) but cannot open

### ISSUE THREAD

**Issue by unicornuniform** [orbbec/ros2_astra_camera#4]
I'm getting this error repeated when I try to launch:

>$ ros2 launch astra_camera astra.launch.xml
> [astra_camera_node-1] [INFO] [1704807741.632269291] [camera.camera]: init done.
> [astra_camera_node-1] [INFO] [1704807741.632322856] [camera.camera]: Waiting for device connection...
> [astra_camera_node-1] [INFO] [1704807741.632536722] [device_listener]: Found 1 devices
> [astra_camera_node-1] [INFO] [1704807741.632566990] [camera.camera]: Trying to open device: 2bc5/0401@1/12
> [astra_camera_node-1] [INFO] [1704807741.755691378] [camera.camera]: Failed to open device: 2bc5/0401@1/12 error: 	Could not > open "2bc5/0401@1/12": No such device (it may have been disconnected)!

>$ lsusb
> Bus 002 Device 002: ID 0bda:0316 Realtek Semiconductor Corp. Card Reader
> Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 001 Device 003: ID 04f2:b5ab Chicony Electronics Co., Ltd Integrated Camera
> Bus 001 Device 006: ID 8087:0a2b Intel Corp. Bluetooth wireless interface
**> Bus 001 Device 012: ID 2bc5:0401 Orbbec 3D Technology International, Inc Astra**
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

With Astra plugged in:

>$ ros2 run astra_camera list_devices_node
>[INFO] [1704808537.597127149] [device_listener]: Found 1 devices
>Device connected: Astra
>URI: 2bc5/0401@1/12
>[ros2run]: Segmentation fault

With Astra unplugged:
>$ ros2 run astra_camera list_devices_node
>[INFO] [1704808550.106668489] [device_listener]: Found 0 devices

**Comment by falinuxKr** [comment]
@uni

> I'm getting this error repeated when I try to launch:
> 
> > $ ros2 launch astra_camera astra.launch.xml
> > [astra_camera_node-1] [INFO] [1704807741.632269291] [camera.camera]: init done.
> > [astra_camera_node-1] [INFO] [1704807741.632322856] [camera.camera]: Waiting for device connection...
> > [astra_camera_node-1] [INFO] [1704807741.632536722] [device_listener]: Found 1 devices
> > [astra_camera_node-1] [INFO] [1704807741.632566990] [camera.camera]: Trying to open device: 2bc5/0401@1/12
> > [astra_camera_node-1] [INFO] [1704807741.755691378] [camera.camera]: Failed to open device: 2bc5/0401@1/12 error: 	Could not > open "2bc5/0401@1/12": No such device (it may have been disconnected)!
> 
> > $ lsusb
> > Bus 002 Device 002: ID 0bda:0316 Realtek Semiconductor Corp. Card Reader
> > Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> > Bus 001 Device 003: ID 04f2:b5ab Chicony Electronics Co., Ltd Integrated Camera
> > Bus 001 Device 006: ID 8087:0a2b Intel Corp. Bluetooth wireless interface
> > **> Bus 001 Device 012: ID 2bc5:0401 Orbbec 3D Technology International, Inc Astra**
> > Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> 
> With Astra plugged in:
> 
> > $ ros2 run astra_camera list_devices_node
> > [INFO] [1704808537.597127149] [device_listener]: Found 1 devices
> > Device connected: Astra
> > URI: 2bc5/0401@1/12
> > [ros2run]: Segmentation fault
> 
> With Astra unplugged:
> 
> > $ ros2 run astra_camera list_devices_node
> > [INFO] [1704808550.106668489] [device_listener]: Found 0 devices

@unicornuniform 
According to `lsusb` command, you might connect your camera to USB 2.0 port. 
Would you connect it to USB 3.0 port? and check the camera is listed at **bus 2**.

**Comment by unicornuniform** [comment]
> @unicornuniform According to `lsusb` command, you might connect your camera to USB 2.0 port. Would you connect it to USB 3.0 port? and check the camera is listed at **bus 2**.

I figured it out - I am running it in Docker but had not sent the /dev/bus/usb/xxx/yyy to the container using the --device argument. My bad. Thanks.
